from __future__ import annotations

from collections.abc import Callable
from typing import Any

from opsarena.engine.handlers.invoice import (
    handle_apply_credit_memo,
    handle_place_payment_hold,
    handle_record_three_way_match,
    handle_record_vendor_refund,
    handle_release_payment_hold,
    handle_remove_from_payment_batch,
    handle_request_credit_memo,
    handle_request_po_change,
    handle_request_revised_invoice,
    handle_stop_payment,
    handle_write_off_small_balance,
)
from opsarena.engine.handlers.kyc import (
    handle_file_ofac_report,
    handle_freeze_payments,
    handle_request_field_correction,
    handle_review_beneficial_owner,
    handle_review_kyc,
    handle_run_sanctions_screen,
    handle_start_edd_review,
    handle_trigger_reverification,
)
from opsarena.engine.handlers.refund import (
    handle_accept_dispute,
    handle_challenge_dispute,
    handle_clear_reserve,
    handle_execute_refund,
    handle_freeze_payouts,
    handle_refund_pre_dispute_alert,
    handle_resolve_prearbitration,
    handle_set_payout_delay_days,
    handle_set_reserve_percent,
    handle_submit_dispute_evidence,
    handle_unfreeze_payouts,
)
from opsarena.engine.handlers.result import TransitionResult
from opsarena.engine.handlers.supervisor import handle_bulk_assign, handle_bulk_route, handle_rebalance_queue
from opsarena.engine.handlers.shared import (
    handle_advance_clock,
    handle_approve,
    handle_assign,
    handle_batch_reorder,
    handle_claim_case,
    handle_close_case,
    handle_defer,
    handle_escalate,
    handle_inspect_audit,
    handle_list_queue,
    handle_log_internal_note,
    handle_open_case,
    handle_pause_sla,
    handle_prioritize,
    handle_query_policy,
    handle_reject,
    handle_reopen_case,
    handle_request_info,
    handle_resume_sla,
    handle_return_to_queue,
    handle_route_case,
    handle_send_to_qa,
    handle_schedule_follow_up,
    handle_search_cases,
    handle_approve_qa,
    handle_fail_qa,
    handle_send_for_secondary_approval,
    handle_send_message,
    handle_view_record,
)
from opsarena.engine.state import WorldState
from opsarena.models import (
    AcceptDisputeAction,
    AdvanceClockAction,
    ApplyCreditMemoAction,
    ApproveQAAction,
    ApproveAction,
    AssignAction,
    BatchReorderAction,
    BulkAssignAction,
    BulkRouteAction,
    ChallengeDisputeAction,
    ClaimCaseAction,
    ClearReserveAction,
    CloseCaseAction,
    DeferAction,
    EscalateAction,
    ExecuteRefundAction,
    FailQAAction,
    FileOFACReportAction,
    FreezePaymentsAction,
    FreezePayoutsAction,
    InspectAuditAction,
    ListQueueAction,
    LogInternalNoteAction,
    OpenCaseAction,
    OpsAction,
    PauseSLAAction,
    PlacePaymentHoldAction,
    PrioritizeAction,
    QueryPolicyAction,
    RebalanceQueueAction,
    RecordThreeWayMatchAction,
    RecordVendorRefundAction,
    RejectAction,
    ReleasePaymentHoldAction,
    RemoveFromPaymentBatchAction,
    RequestFieldCorrectionAction,
    RequestPOChangeAction,
    RequestRevisedInvoiceAction,
    ResolvePrearbitrationAction,
    ReopenCaseAction,
    RefundPreDisputeAlertAction,
    RequestCreditMemoAction,
    RequestInfoAction,
    ResumeSLAAction,
    ReviewBeneficialOwnerAction,
    ReviewKYCAction,
    RunSanctionsScreenAction,
    StartEDDReviewAction,
    StopPaymentAction,
    ReturnToQueueAction,
    RouteCaseAction,
    ScheduleFollowUpAction,
    SearchCasesAction,
    SendToQAAction,
    SendForSecondaryApprovalAction,
    SendMessageAction,
    SetPayoutDelayDaysAction,
    SetReservePercentAction,
    SubmitDisputeEvidenceAction,
    TriggerReverificationAction,
    UnfreezePayoutsAction,
    ViewRecordAction,
    WriteOffSmallBalanceAction,
)

ActionHandler = Callable[[WorldState, Any], tuple[TransitionResult, Any]]

ACTION_HANDLERS: dict[type, ActionHandler] = {
    ListQueueAction: handle_list_queue,
    SearchCasesAction: handle_search_cases,
    OpenCaseAction: handle_open_case,
    ViewRecordAction: handle_view_record,
    QueryPolicyAction: handle_query_policy,
    InspectAuditAction: handle_inspect_audit,
    LogInternalNoteAction: handle_log_internal_note,
    SendMessageAction: handle_send_message,
    RequestInfoAction: handle_request_info,
    AssignAction: handle_assign,
    BulkAssignAction: handle_bulk_assign,
    BulkRouteAction: handle_bulk_route,
    ClaimCaseAction: handle_claim_case,
    ReturnToQueueAction: handle_return_to_queue,
    RouteCaseAction: handle_route_case,
    PrioritizeAction: handle_prioritize,
    BatchReorderAction: handle_batch_reorder,
    ScheduleFollowUpAction: handle_schedule_follow_up,
    SendToQAAction: handle_send_to_qa,
    ApproveQAAction: handle_approve_qa,
    FailQAAction: handle_fail_qa,
    PauseSLAAction: handle_pause_sla,
    ResumeSLAAction: handle_resume_sla,
    EscalateAction: handle_escalate,
    DeferAction: handle_defer,
    ExecuteRefundAction: handle_execute_refund,
    AcceptDisputeAction: handle_accept_dispute,
    ChallengeDisputeAction: handle_challenge_dispute,
    RefundPreDisputeAlertAction: handle_refund_pre_dispute_alert,
    ResolvePrearbitrationAction: handle_resolve_prearbitration,
    SubmitDisputeEvidenceAction: handle_submit_dispute_evidence,
    FreezePayoutsAction: handle_freeze_payouts,
    UnfreezePayoutsAction: handle_unfreeze_payouts,
    SetReservePercentAction: handle_set_reserve_percent,
    ClearReserveAction: handle_clear_reserve,
    SetPayoutDelayDaysAction: handle_set_payout_delay_days,
    RecordThreeWayMatchAction: handle_record_three_way_match,
    PlacePaymentHoldAction: handle_place_payment_hold,
    ReleasePaymentHoldAction: handle_release_payment_hold,
    RequestCreditMemoAction: handle_request_credit_memo,
    SendForSecondaryApprovalAction: handle_send_for_secondary_approval,
    ReviewKYCAction: handle_review_kyc,
    TriggerReverificationAction: handle_trigger_reverification,
    RunSanctionsScreenAction: handle_run_sanctions_screen,
    StartEDDReviewAction: handle_start_edd_review,
    ReviewBeneficialOwnerAction: handle_review_beneficial_owner,
    RequestFieldCorrectionAction: handle_request_field_correction,
    FileOFACReportAction: handle_file_ofac_report,
    FreezePaymentsAction: handle_freeze_payments,
    RebalanceQueueAction: handle_rebalance_queue,
    RequestRevisedInvoiceAction: handle_request_revised_invoice,
    RequestPOChangeAction: handle_request_po_change,
    RemoveFromPaymentBatchAction: handle_remove_from_payment_batch,
    StopPaymentAction: handle_stop_payment,
    RecordVendorRefundAction: handle_record_vendor_refund,
    ApplyCreditMemoAction: handle_apply_credit_memo,
    WriteOffSmallBalanceAction: handle_write_off_small_balance,
    ApproveAction: handle_approve,
    RejectAction: handle_reject,
    CloseCaseAction: handle_close_case,
    ReopenCaseAction: handle_reopen_case,
    AdvanceClockAction: handle_advance_clock,
}


def dispatch_action(state: WorldState, action: OpsAction) -> tuple[TransitionResult, Any]:
    handler = ACTION_HANDLERS.get(type(action))
    if handler is None:
        raise ValueError("unsupported_action")
    return handler(state, action)
